spring:
  batch:
    jdbc:
      initialize-schema: never # Spring Batch관련 테이블 생성 여부 근데 어차피 동작을 안하는 것같으 최신버전에서는...
  datasource:
    url: jdbc:h2:mem:testdb
    path: /h2-console
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true
        logging.level:
        org.hibernate.SQL: debug
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: false # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      encoding: UTF-8
      separator: ; # sql문을 구분할 구분자
  quartz:
    job-store-type: jdbc # jobStore를 jdbc로 사용 (기본 사용시 메모리 사용)
    jdbc:
      initialize-schema: always # 항상 쿼츠 관련 테이블을 drop 후 생성한다.
chunkSize: 5 # Chunk 단위 (한번에 작업하는 트랜잭션 단위)
mybatis:
  configuration:
    map-underscore-to-camel-case: true
